version: '3.3'
services:
  candlepin:
    image: ${REGISTRY}/candlepin-base
    ports:
      - "8443:8443"
      - "8080:8080"
      - "22:22"
    privileged: true
    volumes:
      - ../:/candlepin-dev
