openapi: 3.0.2
info:
  title: Candlepin
  description: Candlepin is a subscription management server written in Java. It helps with management of software subscriptions.
  version: 4.0.0

servers:
  - url: /candlepin

security:
  - basicAuth: []

paths:
  /:
    get:
      description: Retrieves a list of links corresponding to Root resources
      tags:
        - root
      operationId: getRootResources
      security: []  # this resource doesn't require auth
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Link'
        default:
          description: An exception occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExceptionMessage'

components:
  schemas:
    ExceptionMessage:
      description: An exception occurred
      properties:
        displayMessage:
          type: string
        requestUuid:
          type: string

    Link:
      description: Used to represent a link to a top level resource in Candlepin
      properties:
        rel:
          type: string
        href:
          type: string

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
