---
name: Run checkstyle

on:
  pull_request:
  workflow_dispatch:

# Cancel in-progress PR verification workflows. We only care about verifying the latest commit.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    container:
      image: fedora:38
    steps:
      - name: Install dependencies
        shell: bash
        run: dnf --setopt install_weak_deps=False install -y gettext git-core jss

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Rebase
        uses: ./.github/actions/rebase

      - name: Set Environment Variables
        uses: ./.github/actions/set_vars
        with:
          varFilePath: ./.github/variables/pr_verification.env

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run checkstyle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: checkstyle
