name: AutoAssignReviewer

# GH Actions vs Jenkins
#
# Jenkins current state
#
# - Our setup is dated and as such requires additional bookkeeping when making changes
# - Our pipeline is coupled between branches. Meaning that changes in one branch
#    affect other branches. This is mainly cause my sharing agent between them.
#
#
# GH Actions pros and cons
#
# +
# +
# -
# -
#

on:
  pull_request:
    branches:
      - master

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
#      - uses: actions/setup-java@v3
#        with:
#          distribution: temurin
#          java-version: 17
#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew checkstyle
