---
name: Run spec tests

on:
  pull_request:
  workflow_dispatch:

# Cancel in-progress PR verification workflows. We only care about verifying the latest commit.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  spec_tests:
    name: spec tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        database: [postgres, mariadb]
        mode: [standalone, hosted]

    steps:
      - name: Install dependencies
        shell: bash
        run: sudo apt-get install -y gettext git-core

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Rebase
        uses: ./.github/actions/rebase

      - name: Set Environment Variables
        uses: ./.github/actions/set_vars
        with:
          varFilePath: ./.github/variables/pr_verification.env

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - if: matrix.mode == 'standalone'
        name: Add standalone env variable
        working-directory: ./.github/containers
        shell: bash
        run: |
          echo "CANDLEPIN_STANDALONE=true" > .env
          echo "CANDLEPIN_AUTH_CLOUD_ENABLE=false" >> .env
          echo "MODULE_CONFIG_MANIFESTGEN_CONFIGURATION_MODULE=org.candlepin.testext.manifestgen.ManifestGeneratorModule" >> .env

      - if: matrix.mode == 'hosted'
        name: Add hosted env variables
        working-directory: ./.github/containers
        shell: bash
        run: |
          echo "CANDLEPIN_STANDALONE=false" > .env
          echo "MODULE_CONFIG_HOSTEDTEST_CONFIGURATION_MODULE=org.candlepin.testext.hostedtest.HostedTestModule" >> .env
          echo "CANDLEPIN_AUTH_CLOUD_ENABLE=true" >> .env
          echo "MODULE_CONFIG_MANIFESTGEN_CONFIGURATION_MODULE=org.candlepin.testext.manifestgen.ManifestGeneratorModule" >> .env

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Candlepin war file
        run: ./gradlew war -Ptest_extensions=hostedtest,manifestgen

      - uses: actions/cache/restore@v4
        id: restore-tomcat
        with:
          path: apache-tomcat-9.0.76.tar.gz
          key: tomcat-9.0.76

      - name: Ensure Tomcat Artifact
        run: |
          if [ ! -f apache-tomcat-9.0.76.tar.gz ]; then
            wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.76/bin/apache-tomcat-9.0.76.tar.gz \
                -O apache-tomcat-9.0.76.tar.gz
          fi

      - uses: actions/cache/save@v4
        if: steps.restore-tomcat.outputs.cache-matched-key == '' # If cache is not present save tomcat to cache
        with:
          path: apache-tomcat-9.0.76.tar.gz
          key: tomcat-9.0.76

      - name: Create Candlepin and database containers
        shell: bash
        run: |
          WAR_FILE=$(find ./build/libs -name 'candlepin*.war' | head -n 1)
          echo "WAR_FILE=$WAR_FILE" >> ./.github/containers/.env
          docker compose -f ./.github/containers/${{ matrix.database }}.docker-compose.yml --env-file ./.github/containers/.env up --build -d --wait

      - name: Run Spec tests
        run: ./gradlew spec
        env:
          MYSQL_IN_USE: ${{ matrix.database == 'mariadb' }}

      - name: Collect docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@2741064ab9d7af54b0b1ffb6076cf64c16f0220e
        with:
          dest: './logs-${{ matrix.database }}-${{ matrix.mode }}'

      - name: Collect candlepin and Tomcat logs on failure
        if: failure()
        shell: bash
        run: | 
          docker cp candlepin:/var/log/candlepin/ ./logs-${{ matrix.database }}-${{ matrix.mode }}/candlepin/
          docker cp candlepin:/opt/tomcat/logs/ ./logs-${{ matrix.database }}-${{ matrix.mode }}/tomcat/
          
      - name: Collect postgress logs on failure
        if: failure() && matrix.database == 'postgres'
        run:  docker cp postgres:/var/log/postgresql/ ./logs-${{ matrix.database }}-${{ matrix.mode }}/postgresql/

      - name: Collect mariadb logs on failure
        if: failure() && matrix.database == 'mariadb'
        run:  docker cp mariadb:/var/log/mysql/ ./logs-${{ matrix.database }}-${{ matrix.mode }}/mysql/

      - name: Tar logs
        if: failure()
        run: sudo tar cvzf ./logs-${{ matrix.database }}-${{ matrix.mode }}.tgz ./logs-${{ matrix.database }}-${{ matrix.mode }}

      - name: Upload logs to GitHub
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.database }}-${{ matrix.mode }}.tgz
          path: ./logs-${{ matrix.database }}-${{ matrix.mode }}.tgz

      - if: always()
        name: Stop containers
        shell: bash
        run: docker compose -f ./.github/containers/${{ matrix.database }}.docker-compose.yml down
