name: Weekly sonar analysis workflow

on:
  schedule:
    # Every Monday at 1 AM
    - cron:  '0 1 * * 1'

jobs:

  unit_tests:
    runs-on: ubuntu-latest
    container:
      image: quay.io/ojanus/candlepin-jvm11
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run unit tests with test coverage
        run: ./gradlew test coverage
      - name: Stash test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          # TODO limit to only necessary files
          path: build/*

  sonar_analysis:
    needs: unit_tests
    runs-on: ubuntu-latest
    container:
      image: quay.io/ojanus/candlepin-jvm11
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Unstash test reports
        uses: actions/download-artifact@v3
        with:
          name: test-reports
      - name: SonarCloud Scan
        # TODO Skipping for now
        run: echo "Running sonar"
#        uses: sonarsource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        with:
#          projectBaseDir: my-custom-directory
#          args: >
#            -Dsonar.organization=my-organization
#            -Dsonar.projectKey=my-projectkey
#            -Dsonar.python.coverage.reportPaths=coverage.xml
#            -Dsonar.sources=lib/
#            -Dsonar.test.exclusions=tests/**
#            -Dsonar.tests=tests/
#            -Dsonar.verbose=true
